#!/usr/bin/env python3
# RG DS: swap which stick moves the pointer and which scrolls
# (the clicks follow). 
import json
import subprocess

CONF = "/etc/rgds-stick.json"

try:
    with open(CONF) as f:
        s = json.load(f)
except (OSError, ValueError):
    s = {}
s["swap"] = not s.get("swap", False)
try:
    with open(CONF, "w") as f:
        json.dump(s, f, indent=2)
    msg = ("Pointer: right stick, scroll: left stick" if s["swap"]
           else "Pointer: left stick, scroll: right stick")
except OSError:
    msg = f"Cannot write {CONF}; run sudo sh ~/.config/mango/rgds/install.sh"
subprocess.run(["notify-send", "-a", "Sticks", "-t", "3000", msg])
